name: Check Unifi Controller Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  check-unifi-controller-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get Latest Unifi Version
        run: |
          UNIFI_VERSION=$(curl -sX GET "https://fw-update.ubnt.com/api/firmware-latest?filter=eq~~product~~unifi-controller&filter=eq~~platform~~unix&filter=eq~~channel~~release" \
          | jq -r '._embedded.firmware[].version' \
          | awk -F '+' '{print $1}' \
          | tr -d 'v')
          echo "UNIFI_VERSION=$UNIFI_VERSION" >> "$GITHUB_ENV"

      - name: Check for update container image
        run: |
          docker buildx imagetools inspect lscr.io/linuxserver/unifi-network-application:${{ env.UNIFI_VERSION }}
          if [ $? -ne 0 ]; then
            echo "Container image lscr.io/linuxserver/unifi-network-application:${{ env.UNIFI_VERSION }} does not exist. Exiting."
            exit 1
          fi
      
      - name: Update Chart.yaml with new version
        run: |
          #sed -i "s/^version: .*/version: 0.1.0/" unifi-controller/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${{ env.UNIFI_VERSION }}\"/" unifi-controller/Chart.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update unifi-controller version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: helm_appVersion_update
          delete-branch: true
          title: 'Unifi Controller version update'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            unifi_controller_version
            automated pr
          assignees: jsandas
          reviewers: jsandas
          draft: always-true
